from typing import Protocol, TypeVar

T = TypeVar("T")
CreateSchema = TypeVar("CreateSchema")
UpdateSchema = TypeVar("UpdateSchema")


class Repository(Protocol[T]):
    def find_all(self) -> list[T]: ...
    def find_by_id(self, id: str) -> T | None: ...
    def create(self, data: object) -> T: ...
    def update(self, id: str, data: object) -> T | None: ...
    def delete(self, id: str) -> bool: ...
